version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    container_name: fastapi
    restart: always
    ports:
      - 5436:5432
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: